name: galaxy
channels:
  - conda-forge
dependencies:
  - black=22.10.0
  - ca-certificates=2022.9.24
  - click<8.1.0
  - coverage=6.5.0
  - django=4.1.2
  - django-cors-headers=3.13.0
  - django-stubs<1.12.0
  - djangorestframework=3.14.0
  - drf-spectacular=0.24.2
  - flake8=5.0.4
  - go=1.18.5
  - google-auth=2.13.0
  - google-cloud-pubsub=2.13.10
  - google-cloud-secret-manager=2.12.6
  - google-cloud-storage=2.5.0
  - isort=5.10.1
  - mypy=0.942
  - nodejs=18.11.0
  - openssl=3.0.5
  - pillow=9.0.1
  - pip=22.3
  - pre_commit=2.20.0
  - psycopg2=2.9.3
  - python=3.10
  - pyupgrade=3.1.0
  - terraform=1.3.4
  - pip:
    - django-anymail==8.6
    - django-configurations==2.4
    - django-countries==7.4.2
    - django-import-export==3.0.2
    - django-sortedm2m==3.1.1
    - django-storages[google]==1.13.1
    - django-structlog==4.0.1
    - django_rest_passwordreset==1.3.0
    - djangorestframework-simplejwt==5.2.2
    - google-cloud-scheduler==2.7.3
    - google-cloud-tasks==2.12.0
    - requests==2.28.1
    - types-requests==2.28.11.7
