name: galaxy
channels:
  - conda-forge
dependencies:
  - black>=23.0
  - ca-certificates
  - coverage>=7.0
  - flake8>=5.0
  - go=1.18.5
  - isort>=5.10
  - mypy>=1.0
  - nodejs=20
  - openjdk=11
  - openssl
  - pillow>=9.0
  - pip>=24.0
  - pre_commit>=2.20
  - psycopg2=2.9.3
  - python=3.12
  - setuptools>=65.0
  - pyupgrade>=3.1
  - terraform=1.3.4
  - pip:
    - django>=4.2,<5.0
    - django-anymail>=8.6
    - django-configurations>=2.4
    - django-cors-headers>=3.13.0
    - django-countries>=7.4.2
    - django-import-export>=3.0.2
    - django-sortedm2m>=3.1.1
    - django-storages[google]>=1.13.1
    - django-structlog>=4.0.1
    - django-stubs>=1.12.0
    - django_rest_passwordreset>=1.3.0
    - djangorestframework>=3.14.0
    - djangorestframework-simplejwt>=5.2.2
    - drf-spectacular>=0.24.2
    - google-auth>=2.13.0
    - google-cloud-pubsub>=2.13.10
    - google-cloud-scheduler>=2.7.3
    - google-cloud-secret-manager>=2.12.6
    - google-cloud-storage>=2.5.0
    - google-cloud-tasks>=2.12.0
    - requests>=2.28.1
    - types-requests>=2.28.11
